<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Paths.props" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>EpicLoot_UnityLib</RootNamespace>
    <AssemblyName>EpicLoot-UnityLib</AssemblyName>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <!-- Windows-only post-build targets -->
  <Target Name="CopyAssembly" AfterTargets="Build" Condition=" '$(OS)' == 'Windows_NT' ">
    <Copy SourceFiles="$(TargetDir)$(TargetFileName)" DestinationFolder="$(SolutionDir)ValheimUnity\Assets\ExternalLibraries" />
  </Target>
</Project>
